import type { Metadata } from "next";
import LayoutClient from "./layout-client";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang="en">
        <head>
            <Script
                src="/nutrient-viewer/nutrient-viewer.js"
                strategy="beforeInteractive"
            />
        </head>
      <body className={`antialiased`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
